name: feature check

on:
  pull_request:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
      
      - name: Install the project dependencies
        run: npm ci

      - name: Prettier check
        run: npm run prettier

      - name: Lint check
        run: npm run lint

      - name: TS check
        run: npm run tsc
        
      - name: Test
        run: npm test
