name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 모든 히스토리를 가져옵니다. 변경된 파일을 확인하기 위해 필요합니다.

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # 프로젝트에 맞는 Node.js 버전을 지정하세요

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Prettier check
        run: npm run prettier:check -- ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Lint check
        run: npm run lint -- ${{ steps.changed-files.outputs.all_changed_files }}

      - name: TS check
        run: npm run tsc

      - name: Test
        run: npm test
