name: PR check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prettier check
        run: npm run prettier

      - name: Lint check
        run: npm run lint

      - name: TS check
        run: npm run tsc
      - name: Test
        run: npm test